### ISSUE TITLE
Add convenience methods for common prunable conditions

### ISSUE THREAD

**Issue by vassilevsky** [dr2m/activerecord-prunable#1]
This library requires a `prunable` scope in each model. That's fine.

But we noticed that we often define these scopes in the same way:

```ruby
class Entity < ApplicationRecord
  include ActiveRecord::Prunable

  TTL = 7.days

  scope :prunable, -> (time = Time.current) { where('created_at < ?', time - TTL) }
```

It would have been cool if we could write less code for the same effect.

For example:

```ruby
class Entity < ApplicationRecord
  include ActiveRecord::Prunable

  prune_after 7.days
```

Perhaps it will also be nice to have 2 such methods: for `created_at` and for `updated_at` fields, which are standard in all AR models.

If you agree that this is a good idea, but don't have time to implement it, you will get a pull request for it.

What do you think?

**Comment by dr2m** [comment]
Hey, I'm sure that's a great idea. Unfortunately, I'm working hard this week so I've got no time to do that right now. But I'll try my best to implement it at the weekend.

**Comment by vassilevsky** [comment]
Sure! It can wait!

**Comment by dr2m** [comment]
It's done. Sorry for the delay.

Three methods has been added to `0.3.0` version:
`prune_after` (alias for `prune_created_after)
`prune_created_after(TTL)` defines `where('created_at < ?', current_time - TTL)` prunable scope
`prune_updated_after(TTL)` defines `where('updated_at < ?', current_time - TTL)` prunable scope

You can inject current time this way `Prunable.prune!(current_time: Time.current)`

Example:
```
class Entity < ApplicationRecord
  include ActiveRecord::Prunable

  prune_after 7.days
```
```
Entity.prune!(current_time: Time.current)
```

**Comment by vassilevsky** [comment]
Thank you! 👌

**Comment by dr2m** [comment]
It's a shame I've forgotten implement time injection in all models like `Prunable.prune!(current_time: Time.current)
Now it's in 0.3.1. Sorry about that.
