### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Lunacorp** [dr2m/activerecord-prunable#3]
Version 0.3.1 requires the version of Rails < 5.0. Therefore, an error occurs during the installation:
```
Downloading activerecord-prunable-0.3.1 revealed dependencies not in the API or the lockfile (activerecord (< 5.0, >= 3.0), activesupport (< 5.0, >= 3.0)).
```
Can you update the dependencies so that this wonderful library works for Rails 5?
When using version 0.2.1, there was no such problem.

**Comment by dr2m** [comment]
I was sure the gem wouldn't have worked with Rails 5. But I've checked it out, and it works fine.
Dependencies have been actualized in version 0.3.2. Sorry for that.
